name: mattlynaugh
favicon: null
layout_spectrum: 0.25231
typography_spectrum: 0.75835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7099007826764137
  lightness: 0.1811091871932149
  saturation: 0.5582475310657173
  rhythmicContrast: 0.8211476122960448
purpose: []
